services: 
     cpp-backend: 
        build: .
        ports: 
           - "8080:8080"
        networks: 
           - algo-net
     react-ui:
        build: ./frontend
        ports: 
        - "3001:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        stdin_open: true 
        networks:
         - algo-net
networks:
    algo-net:
        driver: bridge        
